# Generated by Django 3.0.6 on 2020-05-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobinator', '0002_auto_20200511_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinator',
            old_name='keyphrase',
            new_name='position',
        ),
    ]
