# Generated by Django 3.0.6 on 2020-05-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0004_auto_20200510_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='posting_url',
        ),
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
