# Generated by Django 3.0.6 on 2020-05-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_auto_20200510_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posting_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_url',
        ),
    ]
