# Generated by Django 3.0.6 on 2020-05-10 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_auto_20200510_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='scraped_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
