# Generated by Django 3.0.6 on 2020-05-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0008_auto_20200510_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(),
        ),
    ]
