# Generated by Django 3.0.6 on 2020-05-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0009_auto_20200510_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
