# Generated by Django 3.0.6 on 2020-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0010_auto_20200510_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
