# Generated by Django 3.0.6 on 2020-05-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0011_auto_20200510_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['created_at']},
        ),
    ]
