# Generated by Django 3.0.6 on 2020-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0012_auto_20200511_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('query_prefix', models.CharField(max_length=250, null=True)),
                ('position_query', models.CharField(max_length=250)),
                ('location_query', models.CharField(max_length=250)),
                ('postings_element', models.CharField(choices=[('', ''), ('div', 'div'), ('a', 'a'), ('p', 'p'), ('span', 'span'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3')], default='', max_length=10)),
                ('postings_class_or_id', models.CharField(max_length=250)),
                ('posting_url_element', models.CharField(choices=[('', ''), ('div', 'div'), ('a', 'a'), ('p', 'p'), ('span', 'span'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3')], default='', max_length=10)),
                ('posting_url_class_or_id', models.CharField(max_length=250)),
                ('posting_title_element', models.CharField(choices=[('', ''), ('div', 'div'), ('a', 'a'), ('p', 'p'), ('span', 'span'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3')], default='', max_length=10)),
                ('posting_title_class_or_id', models.CharField(max_length=250)),
                ('posting_company_element', models.CharField(choices=[('', ''), ('div', 'div'), ('a', 'a'), ('p', 'p'), ('span', 'span'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3')], default='', max_length=10)),
                ('posting_company_class_or_id', models.CharField(max_length=250)),
                ('posting_location_element', models.CharField(choices=[('', ''), ('div', 'div'), ('a', 'a'), ('p', 'p'), ('span', 'span'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3')], default='', max_length=10)),
                ('posting_location_class_or_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
