# Generated by Django 3.0.6 on 2020-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0013_auto_20200602_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
