# Generated by Django 3.0.6 on 2020-06-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0015_auto_20200602_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='website',
            new_name='website_title',
        ),
    ]
